(deftheme hsw-deep-blue
  "Created 2020-07-16.")

(custom-theme-set-faces
 'hsw-deep-blue
 '(mouse ((t (:background "white"))))
 '(cursor ((t (:background "green" :foreground "black"))))
 '(border ((t (:background "black"))))
 '(bold ((t (:bold t :weight bold))))
 '(bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
 '(comint-highlight-input ((t (:bold t :weight bold))))
 '(comint-highlight-prompt ((t (:foreground "cyan"))))
 '(font-lock-builtin-face ((t (:foreground "LightCoral"))))
 '(font-lock-comment-face ((t (:italic t :foreground "CadetBlue" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "gold"))))
 '(font-lock-doc-face ((t (:foreground "BlanchedAlmond"))))
 '(font-lock-function-name-face ((t (:bold t :foreground "goldenrod" :weight bold))))
 '(font-lock-keyword-face ((t (:bold t :foreground "DeepSkyBlue1" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "gold"))))
 '(font-lock-string-face ((t (:foreground "burlywood"))))
 '(font-lock-type-face ((t (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((t (:foreground "SeaGreen2"))))
 '(font-lock-warning-face ((t (:foreground "yellow"))))
 '(fringe ((t (:background "#405060"))))
 '(flyspell-incorrect ((t (:background "light pink" :foreground "orange red" :box (:line-width 2 :color "red2" :style released-button) :underline (:color "magenta" :style wave) :slant oblique))))
 '(header-line ((t (:box (:line-width 2 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
 '(highlight ((t (:background "darkgreen"))))
 '(info-header-node ((t (:foreground "DeepSkyBlue1"))))
 '(info-header-xref ((t (:bold t :weight bold :foreground "SeaGreen2"))))
 '(info-menu-header ((t (:bold t :weight bold))))
 '(info-node ((t (:foreground "DeepSkyBlue1"))))
 '(info-xref ((t (:bold t :foreground "SeaGreen2" :weight bold))))
 '(isearch ((t (:background "palevioletred2" :foreground "brown4"))))
 '(italic ((t (:italic t :slant italic))))
 '(line-number-current-line ((t (:inherit line-number :foreground "dark blue" :background "deep sky blue"))))
 '(menu ((t (:background "gray" :foreground "black"))))
 '(region ((t (:background "DarkCyan"))))
 '(scroll-bar ((t (:background "gray" :foreground "#506070"))))
 '(secondary-selection ((t (:background "yellow" :foreground "gray10"))))
 '(tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(tooltip ((t (:background "lightyellow" :foreground "black"))))
 '(trailing-whitespace ((t (:background "#102e4e"))))
 '(underline ((t (:underline t))))
 '(default ((t (:background "#102e4e" :foreground "#eeeeee" :height 160)))))

(provide-theme 'hsw-deep-blue)
