#!/bin/sh
# copy source-file and Indent using Emacs

ERROR() {
  printf 'error: '
  printf "${@}"
  printf '\n'
  exit 1
}

USAGE() {
  if [ -n "${1}" ]
  then
    printf 'error: '
    printf "${@}"
    printf '\n'
  fi
  echo usage: "$(basename "${0}")" '<options...> <arguments....>'
  echo '       --help                 -h            this message'
  echo '       --verbose              -v            more messages'
  echo '       --copy src dst         -c src dst    copy indented and tabified source to destination'
  echo '       --in-place files...    -i files...   in place tabify and indent of each file'
  echo '       --overwrite            -o            for --copy to overwrite destination'
  echo '       --no-indent            -n            only remove extraneous whitespace, no re-indentation'
  echo '       --debug                -D            debugging messages'
  exit 1
}

EmacsIndentAndTabity() {
  local verbose overwrite source destination out
  verbose="${1}"; shift
  overwrite="${1}"; shift
  source=$(realpath "${1}"); shift
  destination=$(realpath "${1}"); shift

  out='cat > /dev/null'

  [ -f "${source}" ] || USAGE 'source file: "%s" does not exist' "${source}"

  [ -d "${destination}" ] && USAGE 'destination: "%s" cannot be a directory' "${destination}"

  [ -f "${destination}" ] && [ X"${overwrite}" != X"yes" ] && USAGE 'file: "%s" already exists' "${destination}"

  if [ X"${verbose}" = X"yes" ]
  then
    echo "indent/tabify ${source} -> ${destination}"
    out='cat'
  fi

  # use emacs to indent and tabify file
  # and change DOS style EOL (CRLF) to Unix style (LF)
  emacs --batch --execute='
    (progn
      (setq the-source-file "'"${source}"'")
      (setq the-output-file "'"${destination}"'")
      (setq init-dir (expand-file-name (concat "~" init-file-user "/.emacs.d")))
      (load (concat init-dir "/init.el"))
      (find-file the-source-file)
      (set-buffer-file-coding-system '"'"'unix)
      (write-file the-output-file nil)
    )' 2>&1 < /dev/null | eval ${out}
}


# main program
# ------------

verbose=no
overwrite=no
InPlace=no
copy=no
debug=no

getopt=
case "$(uname)" in
  (FreeBSD|DragonFly)
    getopt=/usr/local/bin/getopt
    ;;
  (NetBSD)
    getopt=/usr/pkg/bin/getopt
    ;;
  (OpenBSD)
    getopt=/usr/local/bin/gnugetopt
    ;;
  (Darwin)
    getopt=/usr/local/opt/gnu-getopt/bin/getopt
    ;;
  (Linux)
    getopt=/usr/bin/getopt
    ;;
  (*)
    ERROR 'OS: %s is not supported' "$(uname)"
    ;;
esac
[ -x "${getopt}" ] || ERROR 'getopt: "%s" is not executable or not installed' "${getopt}"

args=$(${getopt} -o hvoicD --long=help,verbose,overwrite,in-place,copy,debug -- "${@}") || exit 1

# replace the arguments with the parsed values
eval set -- "${args}"

while :
do
  case "${1}" in
    (-v|--verbose)
      verbose=yes
      ;;

    (-o|--overwrite)
      overwrite=yes
      ;;

    (-i|--in-place)
      InPlace=yes
      overwrite=yes
      ;;

    (-c|--copy)
      copy=yes
      ;;

    (-D|--debug)
      debug=yes
      ;;

    (--)
      shift
      break
      ;;

    (-h|--help)
      USAGE
      ;;

    (*)
      USAGE 'invalid option: %s' "${1}"
      ;;
  esac
  shift
done

[ X"${debug}" = X"yes" ] && set -x

[ X"${InPlace}" = X"${copy}" ] && USAGE 'must have only one option set'

# execute indent
if [ X"${copy}" = X"yes" ]
then
  [ -z "${1}" ] && USAGE 'missing source file'
  [ -z "${2}" ] && USAGE 'missing destination file'

  EmacsIndentAndTabity "${verbose}" "${overwrite}" "${1}" "${2}"

elif [ X"${InPlace}" = X"yes" ]
then
  for source in "${@}"
  do
    EmacsIndentAndTabity "${verbose}" "${overwrite}" "${source}" "${source}"
  done
fi
